services:
  frontend:
    image: moonbeans/frontend:latest
    build: ./app
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports: 
      - "3000:3000"
  backend:
    image: moonbeans/backend:latest
    build: ./server
    environment:
      - NODE_ENV=production
    ports: 
      - "5001:5001"
    networks:
      - internal
  mongodb:
    image: mongo:latest
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: moonbeans
    volumes:
      - mongo_dbs:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - internal
volumes:
  mongo_dbs:
networks:
  internal: